{% set name = "steinbock" %}
{% set version = "0.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/steinbock-{{ version }}.tar.gz
  sha256: 543c3743f89564f53bc1c8226463d3e2d95740457de59c17fb67c9d7b360130b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - steinbock = steinbock._cli:steinbock_cmd_group

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
  run:
    - anndata
    - click
    - click-log
    - fcswrite
    - h5py
    - imageio
    - networkx
    - numpy
    - opencv
    - pandas
    - python >=3.8
    - scikit-image
    - scipy
    - tifffile
    - xtiff

test:
  imports:
    - steinbock
  commands:
    - pip list
    - which steinbock  # [not win]
    - where steinbock  # [win]
    # - pip check  # Fails due to opencv-python-headless
  requires:
    - pip

about:
  home: https://pypi.org/project/steinbock
  summary: A toolkit for processing multiplexed tissue images
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/BodenmillerGroup/steinbock

extra:
  recipe-maintainers:
    - goanpeca
    - Milad4849
